### ISSUE TITLE
History of frameworks

### ISSUE THREAD

**Issue by harikt** [JetBrains/php-timeline#10]
Hi, 

I am not sure if you guys have came across  https://github.com/pmjones/php-history . It also mentions many of the frameworks and looks missing in 25 Years history.

Just a note. 

Thank you.

**Comment by pronskiy** [comment]
Hi Hari,

Yes, I've even mentioned this repo in the [README](https://github.com/JetBrains/php-timeline/commit/29471b20df9043a02f6226db7412c3e616cb0f69#diff-04c6e90faac2675aa89e2176d2eec7d8R34), it helped a lot. I did not include every framework from the list as I was not sure what was the real impact on PHP history. 

If you think anything specific is missing and should be added, please let me know.

-Roman

**Comment by harikt** [comment]
I am sorry. I didn't noticed that you mentioned credits. I missed to see Solr, Aura, Agavi etc in the list. ie why asked.
